logging:
  level:
    root: WARN
    org:
      hibernate:
        sql: WARN
        type: WARN

---
spring.profiles: dev

logging:
  level:
    root: info
    org:
      hibernate:
        sql: info
        type: trace